[package]
name = "regli"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
color-eyre = "0.6.5"
crossterm = "0.29.0"
tui-input = "*"
regex = "1.11.2"
clap = { version = "4.5.48", features = ["derive"] }
